name: TaskManager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          heroku-session-key: ${{ secrets.SESSION_KEY }}
          heroku-app-name: cryptic-task-manager
          heroku-email: amit-yurist@mail.ru
          branch: main
        env:
          NODE_ENV: production
          HOST: 0.0.0.0
          DB_TYPE: pg
          DB_PORT: 5432
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: npm install
        run: |
          make setup
          make build

      - name: Run linter
        run: make lint

